#path to docker file for run server
services:
  web-app:
    build:
      context: .
    #ports from docker to system
    ports:
      - "8000:8000"
    #folder for docker from local system for dynamic edits code on docker
    volumes:
      - ./service:/service
    #link to db service docker-compose
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

      #command for runserver on docker
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  #database settings and creds
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass